modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/XNet/issues"
displayURL="http://github.com/McJtyMods/XNet/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="xnet"
version="${file.jarVersion}"
displayName="XNet"
#updateJSONURL="http://myurl.me/" #optional
description='''
Powerful item/fluid/energy transfer
'''
[[dependencies.xnet]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnet]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.xnet]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.15-1.1.6,)"
    ordering="AFTER"
    side="BOTH"
